Update file ci for test coverage threshfold PR pass

diff --git a/.github/workflows/storefront-bff-ci.yaml b/.github/workflows/storefront-bff-ci.yaml
--- a/.github/workflows/storefront-bff-ci.yaml
+++ b/.github/workflows/storefront-bff-ci.yaml
@@ -1,4 +1,4 @@
-﻿name: storefront-bff service ci
+name: storefront-bff service ci
 
 on:
   push:
@@ -29,6 +29,8 @@ jobs:
     runs-on: ubuntu-latest
     permissions:
       contents: read
+      pull-requests: write
+      checks: write
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
@@ -40,6 +42,36 @@ jobs:
 
       - name: Run Unit Tests & Generate JaCoCo Report
         run: mvn clean verify -pl storefront-bff -am
+
+      - name: Code Coverage Quality Gate (Console)
+        run: |
+          REPORT_CSV="storefront-bff/target/site/jacoco/jacoco.csv"
+          if [ -f "$REPORT_CSV" ]; then
+            awk -F"," 'NR>1 { missed += $4; covered += $5 } END {
+              if (missed+covered > 0) coverage = (covered/(missed+covered))*100
+              else coverage = 0
+              printf "===========================================\n"
+              printf " STOREFRONT-BFF SERVICE COVERAGE: %.2f%%\n", coverage
+              printf "===========================================\n"
+              if (coverage < 70) {
+                printf " FAILED: Coverage thấp hơn mức tối thiểu 70%%\n"
+                exit 1
+              }
+            }' $REPORT_CSV
+          else
+            echo "::error::Không tìm thấy file jacoco.csv. Kiểm tra cấu hình jacoco-maven-plugin!"
+            exit 1
+          fi
+
+      - name: Add Coverage Report to PR
+        uses: Madrapps/jacoco-report@v1.6.1
+        if: github.event_name == 'pull_request'
+        with:
+          paths: storefront-bff/target/site/jacoco/jacoco.xml
+          token: ${{ secrets.GITHUB_TOKEN }}
+          min-coverage-overall: 70
+          title: 'Báo cáo độ phủ - Storefront BFF Service'
+          update-comment: true
 
       - name: Upload Test & Coverage Artifacts
         uses: actions/upload-artifact@v4
